### ISSUE TITLE
Matrix vector multiplication

### ISSUE THREAD

**Issue by AnouarNechi** [twaclaw/matmult#4]
Hello,
I want to compute a Matrix vector multiplication based on your code .... what should I change?
Can the hls code be adapted to any matrix sizes?

**Comment by twaclaw** [comment]
Hi,
instead of sending two serialized matrices, you would have to send a matrix and a vector. You have to modify the [kernel_mmult](https://github.com/twaclaw/matmult/blob/d649c0500cee29a26a2633277eb77a579ad84a0e/hls/matmult_accel.cpp#L7) function only, I guess.

The size of this approach is limited by the available resources. If you wanna perform larger matrix-matrix multiplications, you would have to use a different approach, i.e. use a systolic array and block matrix multiplication. Have a look at the [Vitis gemm examples](https://github.com/Xilinx/Vitis_Libraries/tree/master/blas/L1).
